### ISSUE TITLE
Collisions!

### ISSUE THREAD

**Issue by zwyber** [zwyber/pie#10]
There are two types of collisions in the game: Object-Object, Object-Wall. The latter can be described as an Object colliding with a mirror object of it's self, so the whole collision thing can be simplified to Object-Object collisions only.

Required are:
- [x] Object collision detection **Paul?**
- [x] Resolve collision between two objects **Yvan and Paul**

**How to resolve a collision?**
We want a mix of elastic and inelastic collisions. A quick way to implement this is to have elastic collisions (which makes it easy to determine the angle etc), and then subtract some energy to make the net collision inelastic. Although this is not a 100% correct situation it is very easy to implement.

**Comment by YvanKlaver** [comment]
Check collisions is implemented. (bool universe::check_collision(Object\* A, Object\* B))
The function takes two object pointers and returns a boolean, true if collision is detected and false if not.

It checks two statements which need to be true
- if distance between the center of A and B is smaller than their radii summed
- if the objects are moving towards each other.

The second statement has been defined as <X_1-X_2, V_2> + <X_2-X_1,V_1> < 0.
This simply says that if the projection of the velocity on the distance to another object (direction) is negative it moves away. This projection is done for both objects and summed, so if one object is moving closer faster than the other is moving away it'll still register a collision

**Comment by zwyber** [comment]
Few extra things to do: (all things for **Paul**)
- [x] Currently all object collisions are elastic, make it possible to have inelastic collisions.
- [x] Do collisions with walls

**Comment by zwyber** [comment]
Wall collision done, but not so pretty. If it works, should be put into a subroutine.

**Comment by zwyber** [comment]
Elastic collisions done as a linear combination of fully elastic and fully inelastic collisions. Not completely sure if this conserves energy, but I do think so :sweat_smile:

**Comment by zwyber** [comment]
It does not appear to be a problem with collisions. Tested it by outputting "Resolving collision" before resolving a collision, but it was never outputted.
