### ISSUE TITLE
Make a window which shows all objects currently in the universe

### ISSUE THREAD

**Issue by zwyber** [zwyber/pie#12]
Using the OpenGL tutorial framework found. See issue #5

This is a task for **Yvan**

**Comment by YvanKlaver** [comment]
We need a specific coordinate system for the physics engine. Currently I interpret this as the window size with the origin at the center. So for the 1024px by 768px this will be xrange = [-512, 512], yrange = [-384, 384]. 

With the current implementation however, we can optimize our coordinate system to be yrange[-1, 1] and scale the xrange accordingly,

**Comment by zwyber** [comment]
I think setting the origin of the window as the origin of the coordinate system is a good idea. I intrepid your suggestion to map the widow width to 1 and scale x accordingly. That is not such a good idea in my opinion, although I do think a scaling parameter is useful. Alternative idea:
- Origin of the window is (0,0) 
- Length of the physics engine is mapped to a certain length in window, e.g. 1 unit of the physics engine is mapped to 50px (irrespective of the direction). This property would be "zoom" and adjustable.

As a first suggestion I would say zoom = 50 [px/m], so an object with radius 1 will be a 100px circle.

**Comment by YvanKlaver** [comment]
Okay so now we have 3 different scales:
- Physics engine 50 [px/m] (axis equal)
- Window size [px] (axis equal)
- Drawcommands [half a screen] (axis non equal)

Note that the Drawcommands have range [-1, 1] on BOTH axis. (also 50px is a good suggestion already used that as basic scale for the circles)

**Comment by YvanKlaver** [comment]
Code for visualization of universe exists in 'Playground.cpp'. Will transfer this to our code this afternoon. Might create a new file with classes for the visualization.
