### ISSUE TITLE
Implement new "read-only property" code style to access position

### ISSUE THREAD

**Issue by zwyber** [zwyber/pie#13]
Instead of accessing objects by `Object->get_position()` also allow access though `instance.position`.
- [x] First stage is to implement the new code structure
- [x] Secondly start converting all existing code
- [x] Thirdly optimize all code to avoid unnecessary copies

**Comment by zwyber** [comment]
```
class A
{
    int _x; // Private variable, it can modify in this class directly    

public:
    A() : x(_x) // Bind reference variable x to _x
    {
    }

    void setX(int x)
    {
        this->_x = x;
    }

    const int &x; // Constant variable
};

// Usage:

int main()
{
    A a;

    a.setX(50);

    cout << a.x << endl; // Correct

    a.x = 12; // Error !

    return 0;
}
```

**Comment by zwyber** [comment]
Shit hit the fan when I tried to do this, so trying this out again later.

**Comment by zwyber** [comment]
It might be a problem that our class name `Object` conflicts with a built-in class `Object` :sob: Maybe rename our `Object` to `Thing`?

**Comment by YvanKlaver** [comment]
I've seen the reference to `Object` multiple times in external files. If it now finally caused a conflict renaming maybe a good option. Call it 'Thing', 'Blob' or something (a bit less? ambiguous), You may choose it.

**Comment by YvanKlaver** [comment]
PAUL WHAT DID YOU DO TO TESTING.CPP IT CAN'T EVEN FIND 'rand()' ;_;. (luckily playground.cpp still compiles)

**Comment by zwyber** [comment]
I didn't do anything? Look at my commits.

Try "Revert to" the arrow right to the VCS buttons top right. Or `std::rand()`?

**Comment by zwyber** [comment]
Done
