### ISSUE TITLE
Make windows resizable

### ISSUE THREAD

**Issue by zwyber** [zwyber/pie#20]

**Comment by YvanKlaver** [comment]
Decoupled the window size from the Universe size. This now goes through global parameter `visual::pixRatio`, this value is defined as the pixels per universe length unit. Changing this parameter can be done outside initialization and works fine.

Still need to fix the actual window resizing.

**Comment by YvanKlaver** [comment]
Resizing is now don via a call back function that's called when the window is resized. The function changes the values `winWidth` and `winHeight` which the draw functions use to normalize. It also updates the openGL viewPort to fit the window.
