### ISSUE TITLE
Testing functions deprecated

### ISSUE THREAD

**Issue by zwyber** [zwyber/pie#39]
The testing functions in `testing.cpp` are so old that they won't run (or even compile). Agree to make them deprecated and no longer touch the file?

Either we could delete the file (and hope we can still find it back in the version history), or just leave it there but that is going to be a risk when handing in the code.

**Comment by YvanKlaver** [comment]
I'd say we delete it. If we want to use those function for actual testing we would need to rewrite everything anyway. If you want a copy for it to rewrite it in an easy manner it's best to do that outside the git-registry.

**Comment by zwyber** [comment]
I support Yvan's suggestion, let's do that
