### ISSUE TITLE
Window resize functions do not work

### ISSUE THREAD

**Issue by zwyber** [zwyber/pie#42]
If setting to NO_RESIZE the drawn universe is empty :(

**Comment by YvanKlaver** [comment]
This was probably a misinterpretation of how the RESIZE labels work. AUTO_RESIZE_FIX is the only label that snaps the universe bounds to the window bounds when creating the window or binding the universe. This means you need to give universe a size upon creation that is not ludicrously big like 640x480, but will fit the window size.
