### ISSUE TITLE
Basic physics engine

### ISSUE THREAD

**Issue by zwyber** [zwyber/pie#9]
Implementing a basic physics engine to allow for position updates of the objects:

It must do the following things:
1. Determine the net force acting on all objects
2. Calculate the new velocity
3. And hence the new position one timestep further

**Comment by zwyber** [comment]
One method of implementation:

```
// Result container
std::map<Object*, std::array<double, 4>> new_pos_vel_universe = 0;

// Loop through all objects and calculate the new position and velocity, which is a function 
/// of Object (allows for easy modification of moving behaviour (e.g. the player) through inheritance)
foreach Object as obj:
// Store the result in a array of 4 doubles
std::array<double, 4> obj_new_pos_vel = obj.calc_new_pos_vel(universe);
// Store this result
new_pos_vel_universe[&obj] = obj_new_pos_vel;


// After the loop update the positions
foreach new_pos_vel_universe as new_obj_pos_vel:
// With the iterator thing access the object* and call the set_position and set_velocity methods
```

The `Object::calc_new_pos_vel(Universe universe)` function would have to do something like this:

```
// Find all other objects
std::array<double, 2> net_force = 0;
foreach universe.get_all_objects_except_id(my id) as obj
double dist = universe.distance_between(obj, myobj)
force = bla bla bla

// Do the euler step thing

// Return the new position and velocity
```

**Comment by zwyber** [comment]
Agreed on this proposal. It will require the following 
- [x] `double Universe::distance_between(Object* A, Object* B)` Returns the distance between two objects. **Arash**
- [x] `array<double, 4> Object::calc_new_pos_vel(Universe universe)` Function which returns the new position and velocity of this particular object. **Paul and Arash**
- [ ] Get some constants eg `G` as gravitational constant into `Universe` **Arash**

**Comment by zwyber** [comment]
Basic runtime iteration thing works, implemented in `Universe::physics_runtime_iteration()`. :smile:

**Comment by zwyber** [comment]
**Arash** has to finish implementing the physics engine.

**Comment by BladeA** [comment]
well I implemented the function I guess with help of your for loop and wrote the test_05 to test. Me and Yvan checked it in Matlab and it is working.
